name: Deploy Automático a AWS

on:
  push:
    branches:
      - main  # Cambia por master si es tu rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Conectarse a AWS y hacer Git Pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: 22
        script: |
          # 1. Entrar a la carpeta
          cd /home/ubuntu/ProductosF
          
          # 2. Actualizar el código
          git pull origin main
          
          echo "¡El código se actualizó correctamente en AWS!"